sudo: required
language: node_js

branches:
  only:
    - master
    
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv -in id_rsa.enc -out id_rsa -d
  - git config --global user.email "609888703@qq.com"
  - git config --global user.name "zhiqiang.huang"

install:
  - docker run --rm -v "$PWD":/gitbook billryan/gitbook gitbook install
  - docker run --rm -v "$PWD":/gitbook billryan/gitbook gitbook build
  
before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script: true

after_success:
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- git fetch --unshallow
- git checkout -b built
- git add -A
- git commit -m 'built version'
- git remote add deploy ssh://root@wiki.sudoso.com:29029/root/gitbook.git
- git push deploy built --force